### ISSUE TITLE
Default 'en' locale causes error after update to 1.0.6

### ISSUE THREAD

**Issue by octaharon** [iamakulov/moment-locales-webpack-plugin#10]
After update to 1.0.6. got an error in my webpack build pipeline:
```Error: MomentLocalesPlugin: Moment.js doesn’t include a locale you specified: en. Check the plugin’s `localesToKeep` option.```
I'm passing `{localesToKeep:['en']}` to the plugin config as before, was working fine pre-update, as the documentation suggests. So it's a regression error, I'd say.

**Comment by iamakulov** [comment]
Whoops, sorry for the issue!

* Did you upgrade your Moment.js version too? 
* Whatʼs the Moment.js version you use? Changes in 1.0.6 seem unrelated to this issue, so I want to understand what exactly to fix to not break something else.
* Could you confirm that you donʼt have this issue in the same setup, but with v1.0.5? You could run `npm install moment-locales-webpack-plugin@1.0.5` to test this version.

**Comment by octaharon** [comment]
```
"moment": "^2.22.1",
"moment-timezone": "^0.5.17"
```
No, I haven't updated both of them for a while, along with 1.0.6 I've installed minor updates to `cross-env`, `uglify-js` and some react libs, I'm sure it's unrelated.

And yes, 1.0.5 fixes it without touching any configuration.

I assume [here's](https://github.com/iamakulov/moment-locales-webpack-plugin/commit/9eed675e519aa88ecb87fecc8e1f42e4c55ef395#diff-168726dbe96b3ce427e7fedce31bb0bc) where the problem arises, but not really sure what's happening exactly

**Comment by iamakulov** [comment]
> I assume here's where the problem arises, but not really sure what's happening exactly

Thanks! Turns out I forgot to publish this change earlier and assumed only #8 made it into version `1.0.6`.

Closed this in #9. Will release a new patch shortly.

**Comment by iamakulov** [comment]
Released this as `moment-locales-webpack-plugin@1.0.7`. Thanks for your patience!
