### ISSUE TITLE
Force localesToKeep to match exactly

### ISSUE THREAD

**Issue by Crashillo** [iamakulov/moment-locales-webpack-plugin#13]
There are some locales which names are included in any other locale names, so `localesToKeep` parameter bring them as well.

For instance:
```
new MomentLocalesPlugin({
    localesToKeep: ['ca'],
  })
```
You'll get `en-ca` and `fr-ca`, besides `ca`

**Comment by iamakulov** [comment]
Thanks for the report! I’ll try to look into that as soon as possible :)

**Comment by iamakulov** [comment]
Published a fix in `1.1.1`. Thanks for the patience :)
