### ISSUE TITLE
add relative node_modules position

### ISSUE THREAD

**Issue by DemonCloud** [iamakulov/moment-locales-webpack-plugin#22]
if my webpack.the build process is not holding on current dir

the plugin can not find "moment"

try to add the "relative" option

in your source code

```javascript
// you dont actrully know where truly moment module
// just give an option. require.resolve the moment relative position
moment = require('moment');
```

**Comment by iamakulov** [comment]
Thanks for the report! Could you provide more details please? What exactly are you running, and what’s the error you’re seeing? (If you can create a small repository with steps to reproduce, that’d be awesome!)

**Comment by iamakulov** [comment]
I’m going to close this for now, but feel free to submit more details!
