### ISSUE TITLE
ERROR:  MomentLocalesPlugin: Moment.js doesn’t include a locale you specified

### ISSUE THREAD

**Issue by ricardogobbosouza** [iamakulov/moment-locales-webpack-plugin#23]
We use this plugin on [moment-module](https://github.com/nuxt-community/moment-module) to  [Nuxt.js](https://nuxtjs.org)

Problem:
https://github.com/nuxt-community/moment-module/issues/25

This is because of this line
https://github.com/iamakulov/moment-locales-webpack-plugin/blob/master/index.js#L64

Can we have an option not to check the current locale?

**Comment by iamakulov** [comment]
Hey @ricardogobbosouza! Sorry, missed your issue – my inbox’s a mess right now 😬

I’ve drafted https://github.com/iamakulov/moment-locales-webpack-plugin/pull/24 as a potential solution to the issue. Here’s the test that (I assume) covers your use-case:

https://github.com/iamakulov/moment-locales-webpack-plugin/blob/e48047247b0fd734896527f3da6dba20e983d576/test/test.js#L116-L128

Could you confirm whether it solves the issue you’re having? If you want to test it locally, this patch is available in npm under `moment-locales-webpack-plugin@1.1.1-0`.

I’ll be happy to publish `1.1.1` as soon as you confirm this works for you.

**Comment by ricardogobbosouza** [comment]
@iamakulov thanks
I will test

**Comment by ricardogobbosouza** [comment]
Its works @iamakulov

**Comment by iamakulov** [comment]
Just released a `@1.1.2` with the fix!

**Comment by ricardogobbosouza** [comment]
thanks @iamakulov
