### ISSUE TITLE
locales in moment/dist/locale are still included

### ISSUE THREAD

**Issue by akonyer** [iamakulov/moment-locales-webpack-plugin#33]
Hey, I'm sure I'm doing something wrong here, but even using this plugin with webpack and moment I am still getting the locales directory in my output.

When I look in the node_modules/moment directory, I see two locale folders.

One in the root, and one in dist/locale

I'm not sure why there are two, but no matter what I do the locales in node_moduels/moment/dist/locale are always included.

This seems to only ignore the root node_modules/moment/locale folder.

Any ideas? I'm at a bit of a loss. Thank you very much

**Comment by iamakulov** [comment]
Thanks for the heads-up! Looks like Moment 2.25.2+ started publishing locale files [under `dist` as well](https://github.com/moment/moment/commit/87994b745c20febf378ccd8f2dc190cd8d225020). Coming up with the fix.

**Comment by iamakulov** [comment]
Okay, actually, it appears like Moment [partially reverted the change in 2.25.3](https://github.com/moment/moment/blob/develop/CHANGELOG.md):

> ### 2.25.3
>
> * Release May 4, 2020
> 
> Remove package.json module property. It looks like webpack behaves differently
> for modules loaded via module vs jsnext:main.
> 
> ### 2.25.2
> 
> * Release May 4, 2020
> 
> This release includes ES Module bundled moment, separate from it's source code
> under dist/ folder. This might alleviate issues with finding the `./locale
> subfolder for loading locales. This might also mean now webpack will bundle all
> locales automatically, unless told otherwise.

I’ve started a discussion about this in https://github.com/moment/moment/commit/0c709ba7e463c12c68d7bf217fbdff4ed3b46f2c. @akonyer For now, feel free to just upgrade your Moment.js version to solve this 🙌

**Comment by akonyer** [comment]
Awesome, thank you very much. Glad to see that it wasn't something I was doing wrong haha

**Comment by akonyer** [comment]
Hey, I finally got around to testing this out. I tried 2.25.3 as well as 2.26 and it's not working in either version. Again I'm not sure if I'm doing something wrong here, but I am definitely seeing locates in both the /dist/locales and /locales directory with both of these versions.

**Comment by iamakulov** [comment]
Hey! Apologies, just got back to this.

Could you please do these three quick things?
* Run webpack-bundle-analyzer (or source-map-explorer, if you’re using CRA) and attach the screenshot of the generated page here
* Tell your exact moment.js version (run `yarn why moment`)
* And show how you’re importing Moment.js (just copy your imports and paste here)

Thanks! Would love to understand how exactly Moment.js is bundled and what’s the best way I can reproduce this.

**Comment by jiangshanglong** [comment]
> Hey! Apologies, just got back to this.
> 
> Could you please do these three quick things?
> 
> * Run [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) (or [source-map-explorer](https://www.npmjs.com/package/source-map-explorer), if you’re using CRA) and attach the screenshot of the generated page here
> * Tell your exact moment.js version (run `yarn why moment`)
> * And show how you’re importing Moment.js (just copy your imports and paste here)
> 
> Thanks! Would love to understand how exactly Moment.js is bundled and what’s the best way I can reproduce this.
I have the same problem,both moment(2.29.3) and moment-locales-webpack-plugin(1.2.0) are latest
1.webpack-bundle-analyze
![企业微信截图_1656475414998](https://user-images.githubusercontent.com/20588463/176355199-461a9b35-9d69-451b-b22f-5b9b28a052a5.png)
2.moment:2.29.3
3.import moment from 'moment';

**Comment by std4453** [comment]
Hi @iamakulov , I'm using `moment@2.29.4` and `moment-locales-webpack-plugin@1.2.0` here and this problem persists. Just wondering whether we can ignore both `locale` and `dist/locale` at the same time, regardless of the version of `moment`?
