### ISSUE TITLE
Webpack Warning: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by hoeni** [iamakulov/moment-locales-webpack-plugin#43]
[Edit: This seems to be related with WebPack in General, not with Angular]
When activating this module in an Angular 12 project, this results in a warning:

`./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:29834:15-36 - Warning: Critical dependency: the request of a dependency is an expression`

When looking at https://github.com/webpack/webpack/issues/196 this seems to be a webpack warning about a require statement using a dynamic path for loading, as this prohibits tree shaking. Maybe there is a way to implement this module's functionality without doing so?

**Comment by iamakulov** [comment]
Hey @hoeni! Thanks for reporting this.

Do you have a reproducible example, by chance? I can’t reproduce the warning with `webpack@5.51.1`, `moment@2.29.1` and `moment-locales-webpack-plugin@1.2.0`.

<img width="962" alt="Screen Shot 2021-08-30 at 19 21 21" src="https://user-images.githubusercontent.com/2953267/131371463-9c16a493-6c27-4428-a7e1-e4de51ad5648.png">

**Comment by sscholle** [comment]
Hi @iamakulov 

I believe the error is caused by a deprecated angular class as commented here: https://github.com/angular/angular/issues/43092#issuecomment-895848535

this is not a webpack issue, it's just that webpack will report it as it prevents optimisations

**Comment by hoeni** [comment]
@iamakulov I'll try to reproduce, have to remember how I worked around this 🙃
@sscholle I don't think this is caused by the angular class, it is just another way to trigger this webpack warning.

**Comment by hoeni** [comment]
I have created a minimum showcase: https://github.com/hoeni/moment-locales-webpack-plugin-demo

This is just
* `ng create`
* `npm i -D @angular-builders/custom-webpack moment moment-locales-webpack-plugin`
* fix angular.json for extra `extra-webpack.config.js`
* provide `extra-webpack.config.js`

When running ng server you get
```
ng serve

⠋ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.09 MB
polyfills.js        | polyfills     | 128.50 kB
main.js             | main          |  54.73 kB
runtime.js          | runtime       |   6.61 kB
styles.css          | styles        | 736 bytes

                    | Initial Total |   2.27 MB

Build at: 2021-09-03T09:46:04.258Z - Hash: 9a2a333dd2cbae0e22e2 - Time: 10838ms

./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:29864:15-36 - Warning: Critical dependency: the request of a dependency is an expression

./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:29876:15-102 - Warning: Critical dependency: the request of a dependency is an expression



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

```

**Comment by ashkan-dev-86** [comment]
> FWIW it also looks like Angular 13 won’t be using `ContextReplacementPlugin` to silence these warnings anymore: [angular/angular-cli@248ed48](https://github.com/angular/angular-cli/commit/248ed4864e0111d1d14f327f59cb08c713926a66). So even if `@angular-builders/custom-webpack-config` doesn’t fix the issue, upgrading to Angular 13 will remove the warning.

This wouldn't remove the warning
